[tox]
envlist =
    ruff
    pylint
    py{310,311,312,313,314}
    pypy{3}
    mypy

[testenv]
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    {envpython} -m tests {posargs}
setenv =
    PYTHONDONTWRITEBYTECODE=1
usedevelop = true

[testenv:mainline]
commands =
    {envpython} -m nfsn_ddns {posargs}
setenv =
    {[testenv]setenv}
    PYTHONUNBUFFERED=1
passenv =
    *

[testenv:ruff]
deps =
    {[testenv]deps}
    ruff: ruff==0.14.10
setenv =
    {[testenv]setenv}
    RUFF_CACHE_DIR={toxworkdir}/.ruff_cache
commands =
    ruff \
    check \
    nfsn_ddns \
    tests

[testenv:pylint]
deps =
    {[testenv]deps}
    pylint: pylint==4.0.4
commands =
    pylint \
    nfsn_ddns \
    tests

[testenv:mypy]
deps =
    {[testenv]deps}
    -r{toxinidir}/requirements_types.txt
    mypy: mypy==1.19.1
commands =
    mypy \
    nfsn_ddns
