name: Build

on:
  push:
    branches:
    - main
    paths:
      - '.github/workflows/build.yml'
      - 'nfsn_ddns/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements_dev.txt'
      - 'requirements_types.txt'
      - 'ruff.toml'
      - 'tox.ini'
  pull_request:
    branches:
    - main
    paths:
      - '.github/workflows/build.yml'
      - 'releng/**'
      - 'nfsn_ddns/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'requirements_dev.txt'
      - 'requirements_types.txt'
      - 'ruff.toml'
      - 'tox.ini'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.img }}
    strategy:
      matrix:
        include:
            - { os:  ubuntu-latest, img: "python:3.9-slim",          python:  "3.9", toxenv:   py39, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, img: "python:3.10-slim",         python: "3.10", toxenv:  py310, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, img: "python:3.11-slim",         python: "3.11", toxenv:  py311, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, img: "python:3.12-slim",         python: "3.12", toxenv:  py312, cache: ~/.cache/pip }
            - { os:  ubuntu-latest, img: "python:3.13-slim",         python: "3.13", toxenv:  py312, cache: ~/.cache/pip }
            - { os:   macos-latest,                                  python: "3.12", toxenv:  py312, cache: ~/Library/Caches/pip }
            - { os: windows-latest,                                  python: "3.12", toxenv:  py312, cache: ~\AppData\Local\pip\Cache }
            - { os:  ubuntu-latest, img: "python:3.13-slim",         toxenv:   lint, cache: ~/.cache/pip }

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      if: ${{ matrix.img == '' }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Cache pip
      uses: actions/cache@v4
      id: cache-pip
      with:
        path: ${{ matrix.cache }}
        key: ${{ matrix.os }}-${{ matrix.python }}-pip

    - name: Setup container cache ownership
      if: ${{ matrix.img != '' }}
      run: |
        mkdir -p ~/.cache
        chown -R $(id -u) ~/.cache

    - name: Install dependencies
      run: python -m pip install --upgrade tox

    - name: tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
